turn_all_on:
  description: restart the device.
  fields:
    id_list: {description: a list to turn on ., example: "switch.a, switch.b"}
turn_on_device:
  description: turn on the device.
  fields:
    id: {description: a list to turn on ., example: "302"}